language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t alireza-chassebi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alireza-chassebi/docker-react npm run test
